language: python
python:
- '2.7'
- '3.2'
- '3.3'
- pypy
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- nosetests
- coverage run --source=objectpath setup.py test
deploy:
  provider: pypi
  user: adriankal
  password:
    secure: bWTP43XxjAIwC6PMmfjt4/dCBenky+zF7empMgzfmkUq5jCoQjCJm4IUdYIdjCKLYEIU1DaOTp7+rqmIZf2d8wWvGAc4+k3vinV9k8WzycpBM+YgnW2knQ5eko93H0lpNOIrat4J0wvc51JjHfj4uqib6SCTaXmBS/kRHmiRkx8=
  on:
    tags: true
    repo: adriank/ObjectPath
after_success:
- coveralls
